config/routes.rb
Rails.application.routes.draw do

resources :playlists do
  resources :songs
end

# good use of nesting resources for this app!

root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  validates :title, presence: true,
                    length: { minimum: 5 }
  has_many :songs, dependent: :destroy
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :playlist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  def index
    @playlists = Playlist.all
  end

  def show
    @playlist = Playlist.find(params[:id])
  end

  def new
    @playlist = Playlist.new
  end

  def edit
    @playlist = Playlist.find(params[:id])
  end

  def create
    @playlist = Playlist.new(playlist_params)

    if @playlist.save
      redirect_to @playlist
    else
      render 'new'
    end
  end

  def update
    @playlist = Playlist.find(params[:id])

    if @playlist.update(playlist_params)
      redirect_to @playlist
    else
      render 'edit'
    end
  end

  def destroy
    @playlist = Playlist.find(params[:id])
    @playlist.destroy

    redirect_to playlists_path
  end

  private
  def playlist_params
    params.require(:playlist).permit(:title, :description, :img_url)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def create
      @playlist = playlist.find(params[:playlist_id])
      @song = @playlist.songs.create(song_params)
      redirect_to playlist_path(@playlist)
    end

    private
      def song_params
        params.require(:song).permit(:title, :artist, :album, :year, :img_url, :song_url)
      end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlaylistApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/playlists/_form.html.erb
<%= form_for :playlist, url: playlists_path do |f| %>

<% if @playlist.errors.any? %>
<div id="error_explanation">
  <h2>
    <%= pluralize(@playlist.errors.count, "error") %> prohibited this playlist from being saved:
  </h2>
  <ul>
    <% @playlist.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</p>

<p>
  <%= f.label :description %><br>
  <%= f.text_field :description %>
</p>

<p>
  <%= f.label :img_url %><br>
  <%= f.text_field :img_url %>
</p>

<p>
  <%= f.submit %>
</p>

<% end %>

app/views/playlists/edit.html.erb
<h1>Edit Playlist</h1>

<%= render 'form' %>

<%= link_to 'Back', playlists_path %>

app/views/playlists/index.html.erb
<h1>Kool Jamz</h1>

<h2>Playlists <a href="/playlists/new">(+)</a></h2>

<ul>
  <% @playlists.each do |playlist| %>
  <li>
    <a href="/playlists/<%= playlist.id %>">
      <%= playlist.title %> <br>
      <%= link_to 'Edit', edit_playlist_path(playlist) %>
      <%= link_to 'Delete', playlist_path(playlist),
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %>
    </a>
  </li>
  <% end %>
</ul>

app/views/playlists/new.html.erb
<h1>New Playlist</h1>

<%= render 'form' %>

<%= link_to 'Back', playlists_path %>

app/views/playlists/show.html.erb
<style>
body {
  background-image: url('<%= @playlist.img_url %>');
  background-size: cover;
}
</style>

<!-- It's better to add classes to style elements then to style them in HMTL with tags like <strong> etc. This way, it's less work if you want to make a stylistic change to all of your headers- you don't have to replace a bunch of strong/i/b/etc tags manually this way.

 In terms of the display, I would also introduce greater visual separation between your songs and the playlist: maybe enlarge the playlist-name header and/or add some space in between the header and songs. Maybe make a separate div for your songs. Overall your views look good. -->
<div>
  <p>
    <strong>Playlist:</strong>
    <%= @playlist.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @playlist.description %>
  </p>

  <h2>Songs</h2>

  <% @playlist.songs.each do |song| %>
  <p>
    <strong>Title:</strong>
    <%= song.title %>
  </p>

  <p>
    <strong>Artist:</strong>
    <%= song.artist %>
  </p>

  <p>
    <strong>Album:</strong>
    <%= song.album %>
  </p>

  <p>
    <strong>Year:</strong>
    <%= song.year %>
  </p>


<% end %>

  <h2>Add a Song:</h2>
  <%= form_for([@playlist, @playlist.songs.build]) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </p>

  <p>
    <%= f.label :album %><br>
    <%= f.text_field :album %>
  </p>
  <p>
    <%= f.label :year %><br>
    <%= f.text_field :year %>
  </p>

  <p>
    <%= f.label :img_url %><br>
    <%= f.text_field :img_url %>
  </p>

  <p>
    <%= f.label :song_url %><br>
    <%= f.text_field :song_url %>
  </p>

  <p>
    <%= f.submit %>
  </p>
  <% end %>

  <p>
    <%= link_to 'Back', playlists_path %>
    <%= link_to 'Edit', edit_playlist_path %>
  </p>
</div>
</body>